blog/urls.py
from django.urls import path

from .views import PostList, PostDetail, PostCreate, PostUpdate, PostDelete

urlpatterns = [
        path('', PostList.as_view(), name='news_list_url'),
        path('post/create/', PostCreate.as_view(), name='post_create_url'),
        path('post/<int:pk>/', PostDetail.as_view(), name='post_detail_url'),
        path('post/<int:pk>/update/', PostUpdate.as_view(), name='post_update_url'),
        path('post/<int:pk>/delete/', PostDelete.as_view(), name='post_delete_url'),
        ]

medical_reports/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import redirect_news
from . import settings

urlpatterns = [
    path('', redirect_news),
    path('news/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('reports/', include('reports.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profiles/', include('profiles.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    if settings.MEDIA_ROOT:
        urlpatterns += static(
                            settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT
                            )
    urlpatterns += staticfiles_urlpatterns()

profiles/urls.py
from django.urls import path

from .views import (
                ProfileDetailView,
                ProfileListView,
                ProfileReportAutofillTemplateCreateView,
                ProfileReportAutofillTemplateUpdateView,
                )


urlpatterns = [
        path('<int:pk>/detail/', ProfileDetailView.as_view(), name='profile_detail_url'),
        path('list/', ProfileListView.as_view(), name='profiles_list_url'),
        path(
             'templates/create_template/',
             ProfileReportAutofillTemplateCreateView.as_view(),
             name='profile_template_create_url'
             ),
        path(
             'templates/<int:pk>/update_template/',
             ProfileReportAutofillTemplateUpdateView.as_view(),
             name='profile_template_update_url'
             )
         ]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError

from reports.models import City, TypeOfVisit


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name=_("User"))
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, verbose_name=_("City"))
    num_col = models.CharField(max_length=9, verbose_name=_("Num. col"))
    is_foreign_doctor = models.BooleanField(default=False, verbose_name=_("Is foreign doctor"))
    initials = models.CharField(max_length=5, verbose_name=_("Initials"), blank=True)
    viber_id = models.CharField(max_length=100, verbose_name=_("Viber id"), blank=True,)
    is_owner = models.BooleanField(default=False, verbose_name=_("Owner"))

    class Meta:
        verbose_name = _('Profile')
        verbose_name_plural = _('Profiles')

    def validate_unique(self, *args, **kwargs):
        super(Profile, self).validate_unique(*args, **kwargs)

        if self.__class__.objects.filter(
                    initials=self.initials,
                    city__district__region__country=self.city.district.region.country
                    ).exclude(pk=self.pk).exists():
            raise ValidationError(
                message=_('Profile with this initials in current country is already exists.'),
                code='unique_together',
            )

        if self.__class__.objects.filter(
                    num_col=self.num_col,
                    city__district__region__country=self.city.district.region.country
                    ).exclude(pk=self.pk).exists():
            raise ValidationError(
                message=_('Profile with this Num. col. in current country is already exists.'),
                code='unique_together',
            )

    def __str__(self):
        return ' '.join((self.user.last_name, self.user.first_name, self.num_col))

    def get_absolute_url(self):
        return reverse('profile_detail_url', kwargs={'pk': self.pk})


class ProfileReportAutofillTemplate(models.Model):
    doctor = models.ForeignKey(
                            Profile,
                            related_name='report_templates',
                            on_delete=models.CASCADE,
                            verbose_name=_("Doctor")
                            )
    country = models.ForeignKey(
                            'reports.Country',
                            related_name='report_templates',
                            on_delete=models.CASCADE,
                            verbose_name=_("Country")
                            )
    name = models.CharField(max_length=100, verbose_name=_("Name"))
    cause_of_visit_template =models.TextField(max_length=700, blank=True, verbose_name=_("Cause of visit"))
    checkup_template = models.TextField(max_length=1200, blank=True, verbose_name=_("Checkup"))
    additional_checkup_template = models.TextField(max_length=700, blank=True, verbose_name=_("Additional checkup"))
    prescription_template = models.TextField(max_length=700, blank=True, verbose_name=_("Prescription"))
    diagnosis_template = models.ManyToManyField(
                                            'reports.Disease',
                                            related_name='autofill_template',
                                            verbose_name=_("Diagnosis"),
                                            blank=True
                                            )

    class Meta:
        unique_together = (('doctor', 'name',),)
        verbose_name = _('Report autofill template')
        verbose_name_plural = _('Report autofill templates')

    def get_update_url(self):
        return reverse('profile_template_update_url', kwargs={'pk': self.pk})


class UserDistrict(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_("User"))
    cities = models.ManyToManyField('reports.City', related_name='cities', verbose_name=_("Cities"))
    country = models.ForeignKey(
                            'reports.Country',
                            related_name='user_district',
                            verbose_name=_("Country"),
                            on_delete=models.CASCADE
                            )

    class Meta:
        verbose_name = _('District coverage')
        verbose_name_plural = _('Districts coverage')

    def __str__(self):
        return ' - '.join((str(self.user.profile), 'district', str(str(self.cities.all()[0].name) + '...')))


class UserDistrictVisitPrice(models.Model):
    user_district = models.ForeignKey(UserDistrict, on_delete=models.CASCADE, verbose_name=_("District"))
    type_of_visit = models.ForeignKey(TypeOfVisit, on_delete=models.CASCADE, verbose_name=_("Type of visit"))
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name=_("Price"))

    class Meta:
        unique_together = (('user_district', 'type_of_visit'),)
        verbose_name = _('Visit price for the doctor')
        verbose_name_plural = _('Visit prices for the doctors')

    def __str__(self):
        return ' - '.join((str(self.user_district), str(self.type_of_visit)))

profiles/forms.py
from django import forms
from django.forms.models import BaseInlineFormSet
from django.utils.translation import ugettext_lazy as _
from django_select2.forms import Select2MultipleWidget

from .models import Profile, ProfileReportAutofillTemplate, UserDistrict
from reports.models import TypeOfVisit


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = []


class ProfileReportAutofillTemplateForm(forms.ModelForm):

    class Meta:
        model = ProfileReportAutofillTemplate
        exclude = ('doctor', 'country')
        widgets = {'diagnosis_template': Select2MultipleWidget, }

    def clean(self):
        cleaned_data = super(ProfileReportAutofillTemplateForm, self).clean()
        return cleaned_data


class UserDistrictVisitPriceInlineFormSet(BaseInlineFormSet):
    def __init__(self, *args, **kwargs):
        if kwargs['instance'].pk:
            type_of_visit_filtered = TypeOfVisit.objects.filter(country=kwargs['instance'].country)
            kwargs['initial'] = [
                {'type_of_visit': type.id, 'price': '-'} for type in type_of_visit_filtered
        ]
        super(UserDistrictVisitPriceInlineFormSet, self).__init__(*args, **kwargs)
        for form in self.forms:
            type_of_visit_field = form.fields['type_of_visit']
            type_of_visit_field.widget.attrs = {'readonly':'readonly'}
            type_of_visit_field.widget.can_add_related = False
            type_of_visit_field.widget.can_change_related = False
            type_of_visit_field.disabled =  True

    def clean(self):
        for form in self.forms:
            try:
                if form.cleaned_data.get('price'):
                    price = form.cleaned_data.get('price')
                    if float(price) < 0:
                        msg = _('The Price can\'t be less than 0')
                        form.add_error('price', msg)
                elif form.cleaned_data.get('price') == 0:
                    msg = _('The Price can\'t be 0')
                    form.add_error('price', msg)
            except ValueError:
                msg = _('The Price should be numeric type')
                form.add_error('price', msg)


class UserDistrictForm(forms.ModelForm):
    class Meta:
        model = UserDistrict
        fields = '__all__'
        exclude = ('cities', 'country', 'user')


class UserDistrictInlineFormset(BaseInlineFormSet):

    def clean(self):
        all_cities = []
        repeated_cities = []
        for form in self.forms:
            country = form.cleaned_data.get('country', False)
            if form.cleaned_data.get('cities', False) and not form.cleaned_data.get('DELETE'):
                cities = form.cleaned_data.get('cities').all()
                for city in cities:
                    if not country == city.district.region.country:
                        form.add_error('cities', _("Cities of the district must belong to the district's country"))
                    all_cities.append(city)

            elif form.cleaned_data.get('cities', False) and form.instance:
                form.add_error('cities', _('At least one city must be chosen'))
        if all_cities:
            for city in all_cities:
                if all_cities.count(city)>1:
                    repeated_cities.append(city)
            for form in self.forms:
                if form.cleaned_data and form.cleaned_data.get('cities'):
                    repeated_case = set(repeated_cities) & set(form.cleaned_data.get('cities'))
                    if bool(repeated_case):
                        form.add_error('cities', _('{} - can\'t be dublicated'.format(', '.join(str(city) for city in repeated_case))))

profiles/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, UpdateView, CreateView, ListView
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.http import HttpResponseForbidden

from .forms import ProfileReportAutofillTemplateForm
from .models import Profile, ProfileReportAutofillTemplate

from reports.models import TypeOfVisit, Disease
from reports.views import  AdminStaffRequiredMixin


class ProfileDetailView(LoginRequiredMixin, DetailView):
    template_name = 'profiles/profile_detail.html'
    model = Profile

    def get(self, request, pk):
        self.object = self.get_object()
        profile_country = self.object.city.district.region.country
        user_country = request.user.profile.city.district.region.country
        country_case = profile_country == user_country
        if country_case and (request.user.profile.pk == pk or request.user.is_staff):
            profile = get_object_or_404(self.model, pk=pk)
            type_of_visit_set = TypeOfVisit.objects.filter(country=profile_country)
            autofill_template_set = self.object.report_templates.filter(country=profile_country)
            context = {
                      'profile'              : profile,
                      'type_of_visit_set'    : type_of_visit_set,
                      'autofill_template_set': autofill_template_set
                    }
            if profile.pk == request.user.profile.pk:
                context['profile_link_active'] = 'active'
            else:
                context['doctors_list_link_active'] = 'active'
            return render(
                        request,
                        self.template_name,
                        context=context)
        else:
            return HttpResponseForbidden('403 Forbidden', content_type='text/html')


class ProfileListView(AdminStaffRequiredMixin, ListView):
    model = Profile
    template_name = 'profiles/profiles_list.html'
    ordering = ('city__district__region',)

    def get_context_data(self, *args, **kwargs):
        context = super(ProfileListView, self).get_context_data()
        context['doctors_list_link_active'] = "active"
        return context

    def get_queryset(self):
        queryset = super(ProfileListView, self).get_queryset()
        doctors_country = self.request.user.profile.city.district.region.country
        queryset = queryset.filter(
                                city__district__region__country=doctors_country, user__is_staff=False
                                )
        return queryset


class ProfileReportAutofillTemplateCreateView(LoginRequiredMixin, CreateView):
    model = ProfileReportAutofillTemplate
    template_name = 'profiles/profile_template_create.html'
    form_class = ProfileReportAutofillTemplateForm

    def get_success_url(self, **kwargs):
        return self.request.user.profile.get_absolute_url()

    def get_context_data(self, **kwargs):
        context = super(ProfileReportAutofillTemplateCreateView, self).get_context_data(**kwargs)
        context['profile_link_active'] = "active"
        context['form'].fields['diagnosis_template'].queryset = Disease.objects.filter(
                                    country=self.request.user.profile.city.district.region.country
                                    )
        return context

    def form_valid(self, form):
        form.instance.doctor = self.request.user.profile
        form.instance.country = self.request.user.profile.city.district.region.country
        form.save()
        return super(ProfileReportAutofillTemplateCreateView, self).form_valid(form)


class ProfileReportAutofillTemplateUpdateView(LoginRequiredMixin, UpdateView):
    model = ProfileReportAutofillTemplate
    template_name = 'profiles/profile_template_update.html'
    form_class = ProfileReportAutofillTemplateForm

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        template_country = self.object.country
        user_country = request.user.profile.city.district.region.country
        country_case = template_country == user_country
        if country_case and (request.user.profile == self.object.doctor or request.user.is_staff):
            return self.render_to_response(self.get_context_data())
        else:
            return HttpResponseForbidden('403 Forbidden', content_type='text/html')

    def get_success_url(self, **kwargs):
        return self.object.doctor.get_absolute_url()

    def get_context_data(self, **kwargs):
        context = super(ProfileReportAutofillTemplateUpdateView, self).get_context_data(**kwargs)
        if self.object.doctor == self.request.user.profile:
            context['profile_link_active'] = "active"
        else:
            context['doctors_list_link_active'] = "active"
        context['form'].fields['diagnosis_template'].queryset = Disease.objects.filter(
                                            country=self.request.user.profile.city.district.region.country
                                            )
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if request.user.profile == self.object.doctor or request.user.is_staff:
            return self.form_valid(form)
        else:
            return HttpResponseForbidden('403 Forbidden', content_type='text/html')

    def form_valid(self, form):
        if self.request.POST.get('Delete'):
            form.instance.delete()
            return redirect(self.get_success_url())
        return super(ProfileReportAutofillTemplateUpdateView, self).form_valid(form)

profiles/templates/profiles/base_profiles.html
{% extends 'base.html' %}
{% load i18n %}

{% block admin-panel-content %}
<a class="admin-panel-element btn btn-success" href="{% url 'report_create_url' %}">{% trans "Create report" %}</a>
{% endblock %}

profiles/templates/profiles/profile_detail.html
{% extends 'profiles/base_profiles.html' %}
{% load i18n %}

{% block title %}
  {{ block.super }} - {% trans "Profile" %}
{% endblock %}


{% block content %}
<div class="container mt-4">
  <div class="row mb-2 border-top">
      <div class="col-md-3">
        <b>{% trans "Last name:" %}</b>
      </div>
      <div class="col">
        {{ profile.user.last_name }}
      </div>
  </div>
  <div class="row mb-2 border-top">
      <div class="col-md-3">
        <b>{% trans "First name:" %}</b>
      </div>
      <div class="col">
        {{ profile.user.first_name }}
      </div>
  </div>
  {% if not profile.user.is_staff %}
  <div class="row mb-2 border-top">
      <div class="col-md-3">
        <b>{% trans "Num. col.:" %}</b>
      </div>
      <div class="col">
        {{ profile.num_col }}
      </div>
  </div>
  {% endif %}
  <div class="row mb-2 border-top">
      <div class="col-md-3 mb-2">
        <b>{% trans "Location:" %}</b>
      </div>
      <div class="col">
        {{ profile.city.district.region.country }}, {{ profile.city.district.region }}, {{ profile.city.name }}
      </div>
  </div>
  <div class="row mb-2 border-top">
    <div class="col-md-3 mb-2">
      <b>{% trans "Initials:" %}</b>
    </div>
    <div class="col">
      {{ profile.initials }}
    </div>
  </div>
  <div class="row mb-2 border-top border-bottom">
    <div class="col-md-3 mb-2">
      <b>Viber: </b>
    </div>
    <div class="col">
      {% if profile.viber_id %}
          <b style="color: green">
            &#10003;
          </b>
      {% else %}
          <b style="color: red">
            &#10005;
          </b>
      {% endif %}
    </div>
  </div>
</div>
{% if not profile.user.is_staff %}
  <table class="table table-bordered mt-4" frame="vsides">
    <td class="table-primary" style="width: 20%">
      <b>{% trans "Territory coverage:" %}</b>
    </td>
    {% for type_of_visit in type_of_visit_set %}
    <td class="table-primary">
      {% if type_of_visit.short_name %}
        {{ type_of_visit.short_name }}
      {% else %}
        {{ type_of_visit.name }}
      {% endif %}
    </td>
    {% endfor %}
    {% for district in profile.user.userdistrict_set.all %}
    {% if district.country == profile.city.district.region.country %}
    <tr>
        <td>

          <br>
          <div class="col font-italic">
            {% for city in district.cities.all %}{{ city.name }}{% if not forloop.last %},{% endif %}
            {% endfor %}
          </div>
        </td>

    {% for type_of_visit in type_of_visit_set %}
        <td>
      {% for visitprice in district.userdistrictvisitprice_set.all %}
        {% if visitprice.type_of_visit == type_of_visit %}
          {{ visitprice.price }} &#8364;
        {% endif %}
      {% endfor %}
        </td>
    {% endfor %}
  </tr>
  {% endif %}
  {% endfor %}
  </table>

  {% endif %}

  {% if autofill_template_set %}
<div class="container">
  <div class="row mb-2 mt-4">
      <div class="col-3">
        <b>{% trans "Autofill templates:" %}</b>
      </div>
  </div>
  {% for template in autofill_template_set %}
  <div class="row">
      <div class="col">
        <a href="{{ template.get_update_url }}">{{ template.name }}</a>
      </div>
  </div>
  {% endfor %}
</div>
  {% endif %}
  {% if profile.user == request.user %}
    <div class="container">
        <div class="row mt-4">
            <div class="col">
                <a class='btn btn-primary' href="{% url 'profile_template_create_url' %}">{% trans "Create template" %}</a>
            </div>
        </div>
    </div>
</div>

  {% endif %}
{% endblock %}

profiles/templates/profiles/profile_template_create.html
{% extends 'profiles/base_profiles.html' %}
{% load static i18n %}

{% block title %}
  {{ block.super }} - {% trans "Create template" %}
{% endblock %}

{% block extrahead %}
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">
  
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    {{ form.media }}
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<form action="{% url 'profile_template_create_url' %}" method="post">
  {% csrf_token %}
  {% for field in form %}
    {% if not field.is_hidden %}
      <div class="form-group col-md-12 mb-2 border-top">
        <div class="form-group col-md-6 mb-0">
          {{ field|as_crispy_field }}
        </div>
      </div>
    {% else %}
      {{ field }}
    {% endif %}
  {% endfor %}
  <div class="form-group col-md-12 mb-2 border-top">
    <div class="form-group col-md-6 mb-0">
      <button type="submit" name="Create" class="btn btn-primary">{% trans "Create template" %}</button>
    </div>
  </div>


</form>
{% endblock %}

profiles/templates/profiles/profile_template_update.html
{% extends 'profiles/base_profiles.html' %}
{% load static i18n %}

{% block title %}
  {{ block.super }} - {% trans "Update template" %}
{% endblock %}

{% block extrahead %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    {{ form.media }}
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<form action="{{ object.get_update_url }}" method="post">
  {% csrf_token %}
  {% for field in form %}
    {% if not field.is_hidden %}
      <div class="form-group col-md-12 mb-2 border-top">
        <div class="form-group col-md-6 mb-0">
          {{ field|as_crispy_field }}
        </div>
      </div>
    {% else %}
      {{ field }}
    {% endif %}
  {% endfor %}
  <div class="form-group col-md-12 mb-2 border-top">
    <div class="form-group col-md-6 mb-0">
      <button type="submit" name="Create" class="btn btn-primary">{% trans "Update template" %}</button>
      <button type="submit" name="Delete" class="btn btn-danger" value='Delete'>{% trans "Delete template" %}</button>
    </div>
  </div>
</form>
{% endblock %}

profiles/templates/profiles/profiles_list.html
{% extends 'profiles/base_profiles.html' %}
{% load i18n %}

{% block title %}
  {{ block.super }} - {% trans "Doctors" %}
{% endblock %}

{% block content %}
<table class="table">
  <thead class="thead-light">
    <th>
        {% trans "Doctor" %}
    </th>
    <th>
        {% trans "City" %}
    </th>
    <th>
        {% trans "Region" %}
    </th>
    <th>
        Viber
    </th>
  </thead>
{% for profile in profile_list %}
  <tr {% if forloop.last %}class="border-bottom"{% endif %}>
    <td>
      <a href="{{ profile.get_absolute_url }}"> {{ profile }}</a>
    </td>
    <td>
      {{ profile.city.name }}
    </td>
    <td>
      {{ profile.city.district.region }}
    </td>
    <td>
      {% if profile.viber_id %}
            <b style="color: green">
              &#10003;
            </b>
      {% else %}
            <b style="color: red">
              &#10005;
            </b>
      {% endif %}
    </td>
  </tr>
{% endfor %}
</table>
{% endblock %}