blog/urls.py
from django.urls import path

from .views import PostList, PostDetail, PostCreate, PostUpdate, PostDelete

urlpatterns = [
        path('', PostList.as_view(), name='news_list_url'),
        path('post/create/', PostCreate.as_view(), name='post_create_url'),
        path('post/<int:pk>/', PostDetail.as_view(), name='post_detail_url'),
        path('post/<int:pk>/update/', PostUpdate.as_view(), name='post_update_url'),
        path('post/<int:pk>/delete/', PostDelete.as_view(), name='post_delete_url'),
        ]

medical_reports/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import redirect_news
from . import settings

urlpatterns = [
    path('', redirect_news),
    path('news/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('reports/', include('reports.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profiles/', include('profiles.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    if settings.MEDIA_ROOT:
        urlpatterns += static(
                            settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT
                            )
    urlpatterns += staticfiles_urlpatterns()

reports/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls import include
from django.views.generic.base import TemplateView
from rest_framework import routers
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token

from .views import (
                ReportsListView,
                ReportDetailView,
                ReportCreateView,
                ReportUpdateView,
                ReportDeleteView,
                ReportAdditionalImagesUpdateView,
                PriceTableView,
                download_report_docx,
                download_reports_excel,
                ReportRequestViewSet,
                RequestOptionsViewSet,
                ReportRequestsView,
                ReportRequestsListView,
                ReportRequestUpdateView,
                vbr_bot,
                ChartsView
                )


router = routers.DefaultRouter()
router.register(r'', ReportRequestViewSet, basename='requests')

urlpatterns = [
        path('', ReportsListView.as_view(), name='reports_list_url'),
        path('create/', ReportCreateView.as_view(), name='report_create_url'),
        path('<int:pk>/update/', ReportUpdateView.as_view(), name='report_update_url'),
        path(
            '<int:pk>/update/images/',
            ReportAdditionalImagesUpdateView.as_view(),
            name='report_images_update_url'
            ),
        path('<int:pk>/view/', ReportDetailView.as_view(), name='report_detail_url'),
        path('price_table/<int:pk>/', PriceTableView.as_view(), name='price_table_url'),
        path('<int:pk>/delete/', ReportDeleteView.as_view(), name='report_delete_url'),
        re_path(
                '(?P<pk>\d+)/view/download/(?P<type_of_report>[a,d])/',
                download_report_docx,
                name='download_report_docx_url'
                ),
        path('download_xlsx/', download_reports_excel, name='download_reports_xlsx_url'),
        path(
            'report_requests_api/options/',
            RequestOptionsViewSet.as_view({"get": "list"}),
            name='report_requests_options_api_url'
            ),
        path('report_requests_api/', include((router.urls, 'requests'))),
        path('report_requests_api/api-auth/', include('rest_framework.urls', namespace='rest_framework')),
        path('report_requests/', ReportRequestsView.as_view(), name='report_requests_url'),
        path('report_requests/history/', ReportRequestsListView.as_view(), name='report_requests_list_url'),
        path('report_requests/history/<int:pk>/edit/', ReportRequestUpdateView.as_view(), name='report_request_update_url'),
        path('viber/viber_webhook_27032020/', vbr_bot),
        path('charts/', ChartsView.as_view(), name='charts_url')
         ]

reports/models.py
import os
import shutil

from viberbot.api.messages.text_message import TextMessage

from django.db import models
from django.shortcuts import reverse
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


def get_image_path(instance, filename):
    return os.path.join(
                    'FILES',
                    str(instance.report.pk),
                    filename
                    )


def get_docxtemplate_path(instance, filename):
    filename = str(instance.country.name) + '_template.docx'
    return os.path.join('DOC_TEMPLATES', filename)


class OverwriteStorage(FileSystemStorage):

    def get_available_name(self, name, max_length=None):
        if self.exists(name):
            self.delete(name)
        return name


class Country(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name=_("Name"))

    class Meta:
        verbose_name = _('Country')
        verbose_name_plural = _('Countries')

    def __str__(self):
        return self.name


class Region(models.Model):
    name = models.CharField(max_length=100, verbose_name=_("Name"))
    country = models.ForeignKey(Country, on_delete=models.PROTECT, verbose_name=_("Country"))
    is_city_state = models.BooleanField(default=False, verbose_name=_("City-state"))

    class Meta:
        unique_together = (('name', 'country',),)
        verbose_name = _('Region')
        verbose_name_plural = _('Regions')

    def __str__(self):
        return self.name


class District(models.Model):
    name = models.CharField(max_length=50, verbose_name=_("Name"))
    region = models.ForeignKey(Region, on_delete=models.PROTECT, verbose_name=_("Region"))

    class Meta:
        unique_together = (('name', 'region',),)
        verbose_name = _('District')
        verbose_name_plural = _('Districts')

    def __str__(self):
        return ' - '.join((str(self.region), self.name))


class City(models.Model):
    name = models.CharField(max_length=100, verbose_name=_("Name"))
    district = models.ForeignKey(District, on_delete=models.PROTECT, verbose_name=_("District"))

    class Meta:
        unique_together = (('name', 'district',),)
        verbose_name = _('City')
        verbose_name_plural = _('Cities')

    def __str__(self):
        return ' - '.join((str(self.name), str(self.district.region.country)))

    def validate_unique(self, exclude=None):
        qs = City.objects.filter(district__region__country=self.district.region.country)
        if self.pk is None:
            if qs.filter(name=self.name).exists():
                raise ValidationError(_("City with this name in the current country is already exists"))

    def save(self, *args, **kwargs):
        self.validate_unique()
        super(City, self).save(*args, **kwargs)


class Disease(models.Model):
    name = models.CharField(max_length=80, unique=True, verbose_name=_("Name"))
    country = models.ForeignKey(Country, on_delete=models.PROTECT, verbose_name=_("Country"))

    class Meta:
        verbose_name = _('Disease')
        verbose_name_plural = _('Diseases')

    def __str__(self):
        return self.name


class PriceGroup(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name=_("Name"))

    class Meta:
        verbose_name = _('Price group')
        verbose_name_plural = _('Price groups')

    def __str__(self):
        return self.name


# Every country must have a list of visit types with appropriative names
class TypeOfVisit(models.Model):
    name = models.CharField(max_length=100, verbose_name=_("Name"))
    short_name = models.CharField(max_length=50, verbose_name=_("Short name"), blank=True)
    is_second_visit = models.BooleanField(default=False, verbose_name=_("Is second visit"))
    country = models.ForeignKey(Country, on_delete=models.PROTECT, verbose_name=_("Country"))
    initial = models.CharField(max_length=2, verbose_name=_("Initial"), blank=True)

    class Meta:
        unique_together = (('name', 'country',),)
        verbose_name = _('Type of visit')
        verbose_name_plural = _('Types of visits')

    def __str__(self):
        if self.short_name:
            return self.short_name
        else:
            return self.name


class Tariff(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE, verbose_name=_("District"))
    price_group = models.ForeignKey(PriceGroup, on_delete=models.CASCADE, verbose_name=_("Price group"))

    class Meta:
        unique_together = (('district', 'price_group',),)
        verbose_name = _('Tariff')
        verbose_name_plural = _('Tariffs')
        ordering = ('price_group',)

    def __str__(self):
        return ' - '.join((str(self.district), str(self.price_group)))


class VisitTariff(models.Model):
    tariff = models.ForeignKey(Tariff, on_delete=models.CASCADE, verbose_name=_("Tariff"))
    type_of_visit = models.ForeignKey(TypeOfVisit, on_delete=models.CASCADE, verbose_name=_("Type of visit"))
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name=_("Price"))

    class Meta:
        unique_together = (('tariff', 'type_of_visit',),)
        verbose_name = _('Visit tariff')
        verbose_name_plural = _('Visit tariffs')

    def __str__(self):
        return ' - '.join((str(self.tariff), str(self.type_of_visit)))


class Company(models.Model):
    name = models.CharField(max_length=20, unique=True, verbose_name=_("Name"))
    price_group = models.ForeignKey(PriceGroup, on_delete=models.PROTECT, verbose_name=_("Price group"))
    initials = models.CharField(max_length=3, verbose_name=_("Initials"), blank=True)

    class Meta:
        verbose_name = _('Company')
        verbose_name_plural = _('Companies')

    def __str__(self):
        return self.name


# Every country need to have template in appropriative language
class ReportTemplate(models.Model):
    template = models.FileField(upload_to=get_docxtemplate_path, storage=OverwriteStorage(), verbose_name=_("Template"))
    country = models.OneToOneField(Country, on_delete=models.CASCADE, verbose_name=_("Country"))

    class Meta:
        verbose_name = _('Report template')
        verbose_name_plural = _('Report templates')


class Report(models.Model):
    company_ref_number = models.CharField(max_length=50, verbose_name=_("Company ref. number"))
    patients_first_name = models.CharField(max_length=50, verbose_name=_("First name"))
    patients_last_name = models.CharField(max_length=50, verbose_name=_("Last name"))
    patients_date_of_birth = models.DateField(verbose_name=_("Date of birth"))
    patients_policy_number = models.CharField(max_length=100, blank=True, verbose_name=_("Policy number"))
    type_of_visit = models.ForeignKey(TypeOfVisit, on_delete=models.PROTECT, verbose_name=_("Type of visit"))
    visit_price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name=_("Visit price"), default=0)
    visit_price_doctor = models.DecimalField(
                                            max_digits=8,
                                            decimal_places=2,
                                            verbose_name=_("Visit price for the doctor"),
                                            default=0
                                            )
    date_of_visit = models.DateField(verbose_name=_("Date of visit"))
    time_of_visit = models.TimeField(null=True, blank=True, verbose_name=_("Time of visit"))
    city = models.ForeignKey(City, on_delete=models.PROTECT, verbose_name=_("City"))
    detailed_location = models.CharField(max_length=100, blank=True, verbose_name=_("Detailed location"))
    cause_of_visit = models.TextField(max_length=700, verbose_name=_("Cause of visit"))
    checkup = models.TextField(max_length=1200, verbose_name=_("Checkup"))
    additional_checkup = models.TextField(max_length=700, blank=True, verbose_name=_("Additional checkup"))
    diagnosis = models.ManyToManyField('Disease', related_name='reports', verbose_name=_("Diagnosis"))
    prescription = models.TextField(max_length=700, verbose_name=_("Prescription"))
    checked = models.BooleanField(default=False, verbose_name=_("Is checked"))
    report_request = models.OneToOneField(
                                        'ReportRequest',
                                        on_delete=models.PROTECT,
                                        related_name='report',
                                        verbose_name=_("Report request")
                                        )

    class Meta:
        verbose_name = _('Report')
        verbose_name_plural = _('Reports')
        permissions = (
            ("can_download_excel", _("Can download excel")),
            )

    def __str__(self):
        return ' '.join((self.patients_last_name, self.patients_first_name, self.get_full_ref_number))

    def get_absolute_url(self):
        return reverse('report_detail_url', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('report_update_url', kwargs={'pk': self.pk})

    def get_images_update_url(self):
        return reverse('report_images_update_url', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('report_delete_url', kwargs={'pk': self.pk})

    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in Report._meta.fields]

    @property
    def get_total_price(self):
        total = 0
        if self.pk:
            services = self.service_items.get_queryset()
            for service in services:
                total += service.cost
            total += self.visit_price
            return total
        return total

    @property
    def get_total_price_doctor(self):
        total = 0
        if self.pk:

reports/templates/reports/base_reports.html
{% extends 'base.html' %}
{% load i18n %}

{% block admin-panel-content %}
<a class="admin-panel-element btn btn-success" href="{% url 'report_create_url' %}">{% trans "Create report" %}</a>
{% endblock %}

reports/templates/reports/report_create.html
{% extends 'reports/base_reports.html' %}
{% load static i18n %}

{% block title %}
  {{ block.super }} - {% trans "Create report" %}
{% endblock %}

{% block extrahead %}
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">
  {{ form.media }}
  <link rel="stylesheet" href="{% static 'node_modules/croppie/croppie.css' %}" />
{% endblock %}

{% block admin-panel-content %}
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
  {% for error in form.non_field_errors %}
  <p style="color: red;">  {{ error|escape }} </p>
  {% endfor %}
</div>

<form action="{% url 'report_create_url' %}" method="post" id="id_visit_failed_form">
  {% csrf_token %}
  <input type="hidden" name="visit_failed" value="True">
  <input type="hidden" name="report_request_failed" value="" id="id_report_request_failed">
</form>

<form action="{% url 'report_create_url' %}" method="post" autocomplete="off" enctype="multipart/form-data" id="id_report_form">
  {% csrf_token %}
  <div class="form-group row border-top">
    <div class="form-group col-md-4 mb-0">
      {{ form.report_request|as_crispy_field }}
    </div>
    <div class="form-group col-md-8 mt-4 overflow-auto mb-0 border" id="id_request_message">
    </div>
    <div class="row">
      <div class="col mt-2 ml-2" id="id_visit_failed_button_div">
      </div>
    </div>
  </div>
  <div class="form-group row border-top">
    <div class="form-group col-md-4 mb-0">
      {{ form.company_ref_number|as_crispy_field }}
    </div>
  </div>
  <div class="form-group row border-top">
    <div class="form-group col-md-4 mb-0">
      {{ form.patients_last_name|as_crispy_field }}
    </div>
    <div class="form-group col-md-4 mb-0">
      {{ form.patients_first_name|as_crispy_field }}
    </div>
  </div>
  <div class="form-group row border-top">
    <div class="form-group col-md-4 mb-0">
      {{ form.patients_date_of_birth|as_crispy_field }}
    </div>
    <div class="form-group col-md-4 mb-0">
      {{ form.patients_policy_number|as_crispy_field }}
    </div>
  </div>
  <div class="form-group row border-top">
    <div class="form-group col-md-2 mb-0">
      {{ form.date_of_visit|as_crispy_field }}
    </div>
    <div class="form-group col-md-2 mb-0">
      {{ form.time_of_visit|as_crispy_field }}
    </div>
    <div class="form-group col-md-4 mb-0">
      {{ form.type_of_visit|as_crispy_field }}
    </div>
  </div>
  <div class="form-group row border-top">
    <div class="form-group col-md-4 mb-0">
      {{ form.city|as_crispy_field }}
    </div>
  </div>
  <div class="form-group row border-top">
    <div class="form-group col-md-4 mb-0">
      {{ form.detailed_location|as_crispy_field }}
    </div>
  </div>
    {% if json_templates %}
  <div class="form-group row border-top">
    <div class="form-group col-md-4 mb-0">
      <label for="id_report_template" class="col-form-label">
                {% trans "Use autocomplete template" %}
      </label>
      <select name="report_template" class="form-control form-control-sm" id="id_report_template">
        <option value=""></option>
        {% for template in json_templates %}
        <option value="{{ template.name }}">{{ template.name }}</option>
        {% endfor %}
      </select>
    </div>
  </div>
  {% endif %}
  <div class="form-group row border-top">
    <div class="form-group col-md-4 mb-0">
      {{ form.diagnosis|as_crispy_field }}
    </div>
  </div>
  <div class="form-group row border-top">
    <div class="form-group col-md-8 mb-0">
      {{ form.cause_of_visit|as_crispy_field }}
    </div>
  </div>
  <div class="form-group row border-top">
    <div class="form-group col-md-8 mb-0">
      {{ form.checkup|as_crispy_field }}
    </div>
  </div>
  <div class="form-group row border-top">
    <div class="form-group col-md-8 mb-0">
      {{ form.additional_checkup|as_crispy_field }}
    </div>
  </div>
  <div class="form-group row border-top">
    <div class="form-group col-md-8 mb-0">
      {{ form.prescription|as_crispy_field }}
    </div>
  </div>
  {% if user.is_staff %}
  <div class="form-group row border-top">
    <div class="form-group col-md-4 mb-0">
      {{ form.visit_price_doctor|as_crispy_field }}
    </div>
    <div class="form-group col-md-4 mb-0">
      {{ form.visit_price|as_crispy_field }}
    </div>
  </div>
  {% endif %}

  <table class="table" id="service_items_table">
    {{ service_items.management_form }}
    {{ service_items.non_form_errors }}
    {% for form in service_items.forms %}
    {% if forloop.first %}
    <thead>
      <tr>
        {% for field in form.visible_fields %}
          {% if not user.is_staff %}
            {% if not field.name == 'cost' and not field.name == 'cost_doctor' %}
              <th>{{ field.label|capfirst }}</th>
            {% endif %}
          {% else %}
            <th>{{ field.label|capfirst }}</th>
          {% endif %}
        {% endfor %}
      </tr>
    </thead>
    {% endif %}
    <tr class="service_formset_row">
      {% if not user.is_staff %}
        {% for field in form.visible_fields %}
          {% if not field.name == 'cost' and not field.name == 'cost_doctor' %}
            <td>
              {% if forloop.first %}
                {% for hidden in form.hidden_fields %}
                  {{ hidden }}
                {% endfor %}
              {% endif %}
                {{ field.errors.as_ul }}
                {{ field }}
            </td>
          {% endif %}
        {% endfor %}
      {% else %}
        {% for field in form.visible_fields %}
          <td>
            {% if forloop.first %}
              {% for hidden in form.hidden_fields %}
                {{ hidden }}
              {% endfor %}
            {% endif %}
              {{ field.errors.as_ul }}
              {{ field }}
          </td>
        {% endfor %}
      {% endif %}
    </tr>
    {% endfor %}
  </table>


  <table class="table" id="images_table">
    {{ images.management_form }}
    {{ images.non_form_errors }}
    {% for form in images.forms %}
    {% if forloop.first %}
    <thead>
      <tr>
        {% for field in form.visible_fields %}
        <th>{{ field.label|capfirst }}</th>
        {% endfor %}
      </tr>
    </thead>
    {% endif %}
    <tr class="images_formset_row">
      {% for field in form.visible_fields %}
      <td>
        {% if forloop.first %}
          {% for hidden in form.hidden_fields %}
            {{ hidden }}
          {% endfor %}
        {% endif %}
        {{ field.errors.as_ul }}
        {{ field }}
      </td>
      {% endfor %}
    </tr>
    {% endfor %}
  </table>

  {% if previous_report %}
      <input type="hidden" name="previous_report" value="{{ previous_report.pk }}">
      {% for image in previous_report.additional_images.get_queryset %}
        <p class='mb-2' style="text-align: center"><img src="{{ image.image.url }}" alt="" width='500px'></p>
      {% endfor %}
  {% endif %}

  <div class="row" id="id_image_crop_set">
  </div>

  <div class="row mb-4">
    <div class="col ml-2">
      <button type="submit" name="Create" class="btn btn-primary" id="id_create">{% trans "Create report" %}</button>
    </div>
  </div>

</form>

<script src="{% static 'node_modules/croppie/croppie.js' %}"></script>
<script type="text/javascript">
jQuery(document).ready(function($) {
function addImageCrop(id){
    var clean_id = id.replace(/\D/g,'');
    var div_id = "id_image_crop_" + clean_id;
    var set = $('#id_image_crop_set');

    if (!($("#" + div_id).length)){
      var div = document.createElement("div");
      var btn_rotate = document.createElement("button");
      btn_rotate.id = 'id_image-rotate_' + clean_id;
      btn_rotate.innerHTML = '&#10227';
      btn_rotate.type = "button";
      div.id = div_id;
      div.style = "text-align: center; z-index: 0";
      div.append(btn_rotate);
      set.append(div);
    } else {
      $("#" + div_id).croppie('destroy')
    }

    var  $uploadCrop;

    function readFile(input) {
      if (input.files && input.files[0]) {
              var reader = new FileReader();
              reader.onload = function (e) {
          $("#" + div_id).addClass('ready');
                $uploadCrop.croppie('bind', {
                  url: e.target.result
                }).then(function(){
                  console.log('jQuery bind complete');
                });
              }
              reader.readAsDataURL(input.files[0]);
          }
          else {
            alert("Sorry - you're browser doesn't support the FileReader API");
        }
    }
    if ($('#'+id)[0].value) {
      $uploadCrop = $("#"+ div_id);
      $uploadCrop.croppie({
      enableExif: true,
      enableOrientation: true,
      enableResize: true,
      mouseWheelZoom: 'ctrl',
      viewport: {
         width: 450,
         height: 350,
         },
      boundary: {
         width: 500,
         height: 400
     }
    });

  readFile($("#id_additional_images-" + clean_id + "-image")[0]);

  $('#id_image-rotate_' + clean_id).on('click', function(ev) {
    $uploadCrop.croppie('rotate', -90);
  });

  $(".croppie-container").sort(function(a, b) {
  if (a.id < b.id) {
    return -1;
  } else {
    return 1;
  }
}).appendTo(set);

    $('#id_report_form').on('submit', function () {
      if ($('#'+id)[0].value) {
        var cropData = $uploadCrop.croppie('get').points;
        var orient = $uploadCrop.croppie('get').orientation;
        $("#id_additional_images-" + clean_id + "-orient").val(orient);
        $("#id_additional_images-" + clean_id + "-x").val(cropData[0]);
        $("#id_additional_images-" + clean_id + "-y").val(cropData[1]);
        $("#id_additional_images-" + clean_id + "-w").val(cropData[2]);
        $("#id_additional_images-" + clean_id + "-h").val(cropData[3]);
      }
  });
}
}
    window.addImageCrop = addImageCrop;
})
</script>

  <script src="{% static 'js/formset/jquery.formset.js' %}"></script>
  <script type="text/javascript">
  $('#service_items_table tbody tr').formset({
    addText: '{% trans "add service item" %}',
    deleteText: '{% trans "remove" %}',
    prefix: '{{ service_items.prefix }}',
    formTemplate: null,
    addCssClass: 'add-row',
    deleteCssClass: 'delete-row',
    formCssClass: 'dynamic-formset1',
    extraClasses: [],
    keepFieldValues: ":input[name$='quantity'],:input[name$='cost'],:input[name$='cost_doctor']",
    added: (row)=>{ row.find('select[name*="service_items"]').djangoSelect2() },
    removed: null
  });
</script>

<script type="text/javascript">
$('#images_table tbody tr').formset({
  addText: '{% trans "add image" %}',
  deleteText: '{% trans "remove" %}',
  prefix: '{{ images.prefix }}',
  formTemplate: null,
  addCssClass: 'add-row',
  deleteCssClass: 'delete-row',
  formCssClass: 'dynamic-formset2',
  extraClasses: [],
  added: null,
  removed: (row)=>{
      var id = row.find('input[name*="id"]')[0].id.replace(/\D/g,'');
      var int_id = parseInt(id);
      if ($("#id_image_crop_" + id).length){
        $("#id_image_crop_" + id).remove();
    }
      if (int_id > 0){
        var crop_divs = $("#id_image_crop_set").children()
        crop_divs.each(function(){
          var int_crop_id = parseInt(this.id.replace(/\D/g,''))
          if (int_crop_id > int_id) {
            $(this)[0].id = this.id.replace(int_crop_id, (int_crop_id - 1));
          }
        });

      }
  }
});
</script>

<script type="text/javascript">
  function selectTemplate(){
    {% autoescape off %}
    var queryset = {{ json_templates }}
    {% endautoescape %}
    var e = $("#id_report_template");
    var name = e[0].value;
    var cause = $("#id_cause_of_visit");
    var check = $("#id_checkup");
    var addit = $("#id_additional_checkup");
    var presc = $("#id_prescription");
    var diag = $("#id_diagnosis");
    if (name){
    var item = queryset.find(item => item.name === name);

    cause.val(item.cause_of_visit_template);
    check.val(item.checkup_template);
    addit.val(item.additional_checkup_template);
    presc.val(item.prescription_template);
    diag.val(item.diagnosis_template).trigger('change');
    }
    else
    {
    cause.val('');
    check.val('');
    addit.val('');
    presc.val('');
    diag.val('').trigger('change');
    }
}

$("#id_report_template").change( function(){
    selectTemplate()
});

</script>

<script type="text/javascript">

  function selectRequest(){
    {% autoescape off %}
    var queryset = {{ json_report_requests }}
    {% endautoescape %}
    let e = $("#id_report_request");
    let pk = Number(e[0].value);
    let message = $("#id_request_message");

    if (pk){
    let item = queryset.find(item => item.pk === pk);
    let el = document.createElement('div');
    let btn = document.createElement('button');

    el.className = 'card-body';
    el.innerHTML = "<pre class='mt-2'>" + item.fields.message + "</pre>";

    btn.type = 'button';
    btn.className = 'btn btn-danger btn-sm';
    btn.innerHTML = "{% trans 'The visit did not take place' %}";
    btn.onclick = function(){
                  let a = confirm("{% trans 'Did this visit really not take place?' %}");
                  if (a == true) {
                      $("#id_visit_failed_form").submit()
                      }
                   };

    message.html(el);
    $("#id_report_request_failed").val(pk);
    $("#id_visit_failed_button_div").html(btn);
    }
    else
    {
    $("#id_report_request_failed").val('');
    message.html('');
    $("#id_visit_failed_button_div").html('');
    }
}

if ($("#id_report_request").val()){
    selectRequest()
};

$("#id_report_request").change( function(){
    selectRequest()
});
</script>
{% endblock %}

reports/templates/reports/report_delete.html
{% extends 'base.html' %}
{% load i18n %}

{% block admin-panel-content %}
{% endblock %}

{% block title %}
{{ block.super }} - {{ report.ref_number }} - {% trans "Delete report" %}
{% endblock %}


{% block content %}
<form action="{{ report.get_delete_url }}" method="post">
  {% csrf_token %}
  <div class="text-center mt-5">
   <h3>{% trans "Are you sure you want to delete" %} <b>"{{ report }}"</b> {% trans "report?" %}"</h3>
   <a href="{{ report.get_absolute_url }}">{% trans "Cancel" %}</a>
   <button type="submit" class="btn btn-danger ml-3">{% trans "Delete" %}</button>
  </div>
</form>
{% endblock %}